apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greatbunny.fullname" . }}-lb
  labels:
    {{- include "greatbunny.labels" . | nindent 4 }}
    app.kubernetes.io/component: lb
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
      worker_connections 10240;
      multi_accept on;
    }

    http {
      add_header Strict-Transport-Security "max-age=63072000; includeSubdomains;" always;
      add_header X-Frame-Options "deny" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header X-Content-Type-Options "nosniff" always;
      # add_header Content-Security-Policy "default-src 'self'" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;

      upstream backends {
        server {{ include "greatbunny.fullname" . }}-backends.greatbunny.svc.cluster.local:80;
      }

      upstream wsgw {
        server {{ include "greatbunny.fullname" . }}-wsgw.greatbunny.svc.cluster.local:80;
      }

      upstream cms {
        server {{ include "greatbunny.fullname" . }}-cms.greatbunny.svc.cluster.local:80;
      }

      upstream game {
        server {{ include "greatbunny.fullname" . }}-game.greatbunny.svc.cluster.local:80;
      }

      server {
        listen 80;

        location /ping {
          return 200 OK;
        }

        location /nginx-status {
          stub_status on;
        }

        location /api/ {
          proxy_pass http://backends/;
        }

        location /wsgw/ {
          proxy_pass http://wsgw/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection Upgrade;
        }

        location /cms/ {
          proxy_pass http://cms/;
        }

        location / {
          proxy_pass http://game/;
        }
      }
    }
    