apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
        kubernetes.io/hostname: "master"
     dataRaidGroups:
      - blockDevices:
          - blockDeviceName: "sparse-a67ba23bfaa2ad15157d33eb4b9deb4d"
     poolConfig:
        dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker-1"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "sparse-3dd89a3dee3cda50a890f0e7bc20513d"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker-2"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "sparse-2f75b0b736510af9414b285198f7472c"
     poolConfig:
       dataRaidGroupType: "stripe"
