apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
        kubernetes.io/hostname: "master"
     dataRaidGroups:
      - blockDevices:
          - blockDeviceName: "blockdevice-38fdf0725204ff366dfd7f441c4a1f4e"
     poolConfig:
        dataRaidGroupType: "stripe"
        
   - nodeSelector:
       kubernetes.io/hostname: "worker-1"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-5162f6f8205f59601edd344752e286c5"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "worker-2"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-03c6725f41e5156dfc1b05175ec97d1a"
     poolConfig:
       dataRaidGroupType: "stripe"
