apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oauth2-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: oauth2
  template:
    metadata:
      labels:
        {{- include "oauth2-proxy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oauth2
    spec:
      imagePullSecrets:
        - name: {{ include "oauth2-proxy.fullname" . }}-registry
      containers:
        - name: {{ include "oauth2-proxy.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - --http-address=0.0.0.0:8080
            - --whitelist-domain=.hellking.dev
            - --provider=oidc
            - --cookie-domain=.hellking.dev
            - --email-domain=*
            - --cookie-secret=y0ur_s3cr3t_v3ry_l0ngggg
            - --client-id=oauth-proxy
            - --client-secret=22F0lclRWWPCQIIJFUUp4gJ3WIuqSGW8
            - --oidc-issuer-url=https://keycloak.hellking.dev/realms/master
            - --redirect-url=https://auth.hellking.dev/oauth2/callback
            - --session-store-type=redis
            - --redis-connection-url=redis://:BOcRpPos23@redis-master-0.redis-headless:6379
            - --redis-connection-idle-timeout=14
