apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2
spec:
  ingressClassName: nginx
  rules:
  - host: auth.hellking.dev
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "oauth2-proxy.fullname" . }}-service
            port:
              name: http
        pathType: Prefix
  tls:
  - hosts:
    - auth.hellking.dev
    secretName: tls-auth-ingress
