apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZWxvZnVuLm5ldCI6eyJ1c2VybmFtZSI6InJvYm90JGRldmVsb3AiLCJwYXNzd29yZCI6InZKYXBwQUVHOG1GYjQyMG5ZYTM3d2dMUjJPMms2Yk9aIiwiYXV0aCI6ImNtOWliM1FrWkdWMlpXeHZjRHAyU21Gd2NFRkZSemh0Um1JME1qQnVXV0V6TjNkblRGSXlUekpyTm1KUFdnPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: oauth2
  name: {{ include "oauth2-proxy.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
