apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-service
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oauth2-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2

---
