apiVersion: v1
kind: Service
metadata:
  name: {{ include "youtrack.fullname" . }}
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
    app.kubernetes.io/component: youtrack
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "youtrack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: youtrack
