apiVersion: v1
kind: Service
metadata:
  name: {{ include "greatbunny.fullname" . }}-wsgw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greatbunny.labels" . | nindent 4 }}
    app.kubernetes.io/component: wsgw
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "greatbunny.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wsgw