apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greatbunny.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greatbunny.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  selector:
    matchLabels:
      {{- include "greatbunny.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        {{- include "greatbunny.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
      annotations:
        checksum/configuration: {{ include (print $.Template.BasePath "/backends/cm.yml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ include "greatbunny.fullname" . }}-registry
      initContainers:
        {{- if not .Values.common.secret_name }}
        - name: wait-database
          image: {{ .Values.common.waitReady.image }}:{{ .Values.common.waitReady.tag | default "latest" }}
          env:
            - name: SERVICE
              value: "{{ include "greatbunny.fullname" . }}-postgres-postgresql"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PORT
              value: "5432"
        {{- end }}
        - name: wait-nats
          image: {{ .Values.common.waitReady.image }}:{{ .Values.common.waitReady.tag | default "latest" }}
          env:
            - name: SERVICE
              value: {{ include "greatbunny.fullname" . }}-nats
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PORT
              value: "4222"
        - name: init-db
          {{- if .Values.backends.tag }}
          image: {{ .Values.backends.image }}:{{ .Values.backends.tag }}
          {{- else }}
          image: {{ .Values.backends.image }}
          {{- end }}
          command:
            - bash
            - -c
            - |
              npx prisma migrate deploy
          env:            
            - name: DATABASE_URL
            {{- if .Values.common.secret_name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.secret_name }}
                  key: db_url
            {{- else }}
              value: {{ .Values.common.db_url }}
            {{- end }}
            - name: REDIS_HOST
            {{- if .Values.common.secret_name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.secret_name }}
                  key: redis_url
            {{- else }}
              value: {{ .Values.common.redis_host }}
            {{- end }}
            - name: REDIS_PORT
              value: {{ .Values.common.redis_port | quote }}
            - name: REDIS_PASSWORD
            {{- if .Values.common.secret_name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.common.secret_name }}
                  key: redis_password
            {{- else }}
              value: {{ .Values.common.redis_password }}
            {{- end }}
      containers:
        - name: scheduler
          {{- if .Values.backends.tag }}
          image: {{ .Values.backends.image }}:{{ .Values.backends.tag }}
          {{- else }}
          image: {{ .Values.backends.image }}
          {{- end }}
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - yarn start:scheduler
          envFrom:
            - configMapRef:
                name: {{ include "greatbunny.fullname" . }}-backends