apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
stringData:
  # the data is abbreviated in this example
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE9jCCA96gAwIBAgISBJEhV0iwsrybFvysgFxtCC+nMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMzExMjMwNDM4MzVaFw0yNDAyMjEwNDM4MzRaMCAxHjAcBgNVBAMT
    FWtleWNsb2FrdjIuZWxvZnVuLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBAKAlgPF+n/isu+dWkSaqjjK9yV1ebULFRR0rmCHw3Kas8gvyDj/ozyTu
    MCgT9R9lbS6yQQnBbp7EMeol3H+gfWnyKnn2U4hyYmMl2oaJaxWXX0BuDW3nn60U
    YnQb6VL0fBfScYfcwVGEA0KVcs5lk71o2uW3Pc7mN8B7E9UEyF0y1GR4iTQyAW3c
    28aheUAHuh4cqc19i1kU6zohzA3z9ot4MFJaFdA2voq0zY4GCWWXEpbZXiVdyqTW
    tWdpAQXwPb2YYl90ycgfKZ//aWx/oZIiKAMV/rUnyLYkR39b2lC2kE9HZCbkKC9x
    x1Op9G+ixWGRI0LaxAKjrY975pdT3IECAwEAAaOCAhYwggISMA4GA1UdDwEB/wQE
    AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
    ADAdBgNVHQ4EFgQUM7FFzJpQxJloqandFcJc9U0Mq8cwHwYDVR0jBBgwFoAUFC6z
    F7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVo
    dHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxl
    bmNyLm9yZy8wIAYDVR0RBBkwF4IVa2V5Y2xvYWt2Mi5lbG9mdW4ubmV0MBMGA1Ud
    IAQMMAowCAYGZ4EMAQIBMIIBAwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYASLDja9qm
    RzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMAAAGL+q/sngAABAMARzBFAiBGyAU1
    QJpMWADzIEFCBoCAIeQEjYBEKXOH05d987+vUgIhAKK/qlcch6ETnJIeiS9cBLr+
    6GwwSND99SnhTlHV2LOcAHUA7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEf
    tZsAAAGL+q/snwAABAMARjBEAiB/Tb48MLMXULk30XtmzXOeNsuy/B97dgO+3UCo
    Jwi6mQIgSs9Aj9JNBGPlENOiJj6ndPCt4aMb3NB01352L1/OsRUwDQYJKoZIhvcN
    AQELBQADggEBAC2A2xPsAuggB+A8t1iMF4RTwSKJbQWuMcqcPEhNEmhu7+OniRHy
    O6ScAtw/jOuGVkvCF/W/FgU1ESSeZiepZCfaeDOiRHQvQSTaPD3MyzyPUdXzeD0t
    mBpaaflP4NvWMU1L0kQYrH7x4SXZZFUHrEbv51ADoBXGPQ1y1lTHFDKmhdFNmWok
    LUiXSbmPUI0dwTTG9KJCquYF2YgFud5MlrVXCa0RcP3lHoNaQbpI+TVBbRl4nUyR
    o1yiUZRxzIC0AaZII8dNDauAujRqea88pPbdkVdbO7Ts5nBoONYC1iSAt8sn8vY7
    fBax3qvFrjFHgK1RLbOKAkDy6sxWiMJhhls=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
    ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
    wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
    LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
    4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
    bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
    sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
    Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
    FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
    SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
    PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
    TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
    c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
    +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
    ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
    b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
    U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
    MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
    5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
    9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
    WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
    he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
    Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAoCWA8X6f+Ky751aRJqqOMr3JXV5tQsVFHSuYIfDcpqzyC/IO
    P+jPJO4wKBP1H2VtLrJBCcFunsQx6iXcf6B9afIqefZTiHJiYyXaholrFZdfQG4N
    beefrRRidBvpUvR8F9Jxh9zBUYQDQpVyzmWTvWja5bc9zuY3wHsT1QTIXTLUZHiJ
    NDIBbdzbxqF5QAe6HhypzX2LWRTrOiHMDfP2i3gwUloV0Da+irTNjgYJZZcSltle
    JV3KpNa1Z2kBBfA9vZhiX3TJyB8pn/9pbH+hkiIoAxX+tSfItiRHf1vaULaQT0dk
    JuQoL3HHU6n0b6LFYZEjQtrEAqOtj3vml1PcgQIDAQABAoIBABiz0EDv9EMKee2E
    N92L/2UqSy5Ay3+6KCAIwm2x1odLNAbNro8DHTioGPuFoJDYN1A1pLyZfrO0tbJV
    Zr61BcNa3Fx1t4rbgfujMiMAfWkWMVYh46ZpTQMImusoBwSJu7588pAvaA5n24zg
    upXFq1VTIDjA3CLW9hCVq4h3NWTSnONZtp8ANoXVUFU/qvXaRmnzUVNxIqT3DFA4
    VDYm++VzupbmcjSGhoQHpT6Q2k62PobmwyyMEoy6pe5fxTiAoS90r2rXpRLRkga2
    t1Dlz5fKLdRct4dMJuYKHjbOL2Ig2IzwpIZDsx8WG7+mVTvmR3S2OoJds4Yuy+Rv
    qmRhoAUCgYEAymG0xwxEdSfICvX0H6IXwmx0s0bDUNWNNWeEiWHPuN7PpsVgauw5
    mIZYB3EIJnuBw3vbhLfde/orZ3s3fsZvKuqeqYb5gE2da6dYrt+wlBCzNXM/vsGf
    qjFqWTnVBQNqqnjGKTdKKPZtFX4WqEZd2L8PE4rMxrD2rMvSeB/at4sCgYEAypM/
    ffc78AyMpP2NG3vr27sIY8EwVl4b7KRutDz9Xg2BtvDNK7Biq9cUPTTeqkaT5cEI
    lbQfnjBf7Gy+06hf4bgCO+84j3zR/2a3PTtDLRHCrZ3GzhGs4nhxmVy9GQKit2yr
    yb160DoTfPBKRCCr4fLEh/4lZEOP7d3iIt+a3aMCgYBXfZ3VXyxJKYWFl4aOFlkH
    KDPbPQA69dcx+yqE6dAPL+O9SR7BmpXbplhv/yFy4XnbtLPV0Fbjveb9uXroR4jP
    mNY2m69JFES1wYbJMtL3b7DJrqUkJjiMLwi2whWhMTTvtX6VWt2oj7/gxr2syZ7Q
    kOhHnn2gd+hsE0FNxRecuQKBgAr9D82icqLj22E7y8K45yNlMuBOY3Pb6QHeLY8j
    W88VRnsI9uguyjtuEE/9pTJxX6Zv4SpVuf1XvGxTvco3cPQKijx8DoJiD/YduUTe
    CRfRxdCrJVSaStmCFQ9vo2ZO6Uqv32WzHI1dCR+W3UBy0UARbi2+UILu00jg51pi
    7MCnAoGAMisKFnbW1VPulAEteuILe2EHJ9kiwwhKKDgjQXsThnP2LzazYCeV6MAi
    eo+EgXWByPkNCzvFITEWtGVDzD116Okt6nNI2GeJTj/d8dpr90L0Om3P8y/yusqL
    va26oxRznQ0gKnAZeBxW2btntty7pvxWrMpe6G8cvtu6JaFJUL0=
    -----END RSA PRIVATE KEY-----
    
